### ISSUE TITLE
Couldn't start the app

### ISSUE THREAD

**Issue by adhrinae** [theCrab/vanman-angular#1]
- Looks like `package.json` file doesn't have scripts for `start` in order to run the server.
- And the `test` as well.

**Comment by theCrab** [comment]
Sorry @emaren84 I did update the app correctly but it was moved away to bitbucket. Just use `gulp default` to run the app after installing the decencies i.e. `npm install`

**Comment by adhrinae** [comment]
I see. I wish I could get some hints for building AngularJS app with Hanami backend. but the source hasn't too much information.

README was great though. Thanks anyway.
